# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=200)),
                ('typename', models.CharField(max_length=200)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=200)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=200)),
                ('productlongname', models.CharField(max_length=200)),
                ('isxf', models.CharField(max_length=200)),
                ('pmdesc', models.CharField(max_length=200)),
                ('specifics', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('marketprice', models.CharField(max_length=200)),
                ('categoryid', models.CharField(max_length=200)),
                ('childcid', models.CharField(max_length=200)),
                ('childcidname', models.CharField(max_length=200)),
                ('dealerid', models.CharField(max_length=200)),
                ('storenums', models.CharField(max_length=200)),
                ('productnum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mainshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('categoryid', models.CharField(max_length=200)),
                ('brandname', models.CharField(max_length=200)),
                ('img1', models.CharField(max_length=200)),
                ('childcid1', models.CharField(max_length=200)),
                ('productid1', models.CharField(max_length=200)),
                ('longname1', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=200)),
                ('marketprice1', models.CharField(max_length=200)),
                ('img2', models.CharField(max_length=200)),
                ('childcid2', models.CharField(max_length=200)),
                ('productid2', models.CharField(max_length=200)),
                ('longname2', models.CharField(max_length=200)),
                ('price2', models.CharField(max_length=200)),
                ('marketprice2', models.CharField(max_length=200)),
                ('img3', models.CharField(max_length=200)),
                ('childcid3', models.CharField(max_length=200)),
                ('productid3', models.CharField(max_length=200)),
                ('longname3', models.CharField(max_length=200)),
                ('price3', models.CharField(max_length=200)),
                ('marketprice3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mustbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trackid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trackid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trackid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trackid', models.CharField(max_length=200)),
            ],
        ),
    ]
