# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='/static/uploads/axf.png', max_length=255),
        ),
    ]
