# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_auto_20181101_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
