# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_auto_20181101_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
