# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.User')),
            ],
        ),
    ]
